### ISSUE TITLE
Repeated toggling of winbox display-hide will cause exceptions

### ISSUE THREAD

**Issue by itmanyong** [wobsoriano/vue-winbox#10]
Repeated switching of container component uninstallation and initialization winbox will error out. If you have the following component structure:
```js
// ParentComponent    visible default is false
<ParentComponent>
  <WinBoxWrapper v-if="visible"></WinBoxWrapper>
</ParentComponent >

// WinBoxWrapper 
<div>
   <VueWinBox></VueWinBox>
</div>
```
1.Change the value of visible from false to true and then to false again
2.At this time there is no problem, then change the value of visible to true again, then it will report an error and winbox will not appear.
tips:The specific errors are as follows
![image](https://user-images.githubusercontent.com/53500371/192984967-e76168f0-3880-486c-a290-ee4b79e1661a.png)

**Comment by wobsoriano** [comment]
Fixed in https://github.com/wobsoriano/vue-winbox/pull/12
