### ISSUE TITLE
Controls not working with vite ?

### ISSUE THREAD

**Issue by cpetreg** [wobsoriano/vue-winbox#13]
I use vuejs3 + vite + vue-winbox 0.2.1:

```
<template>
  <VueWinBox :options="options"></VueWinBox>
</template>

<script setup>
import VueWinBox from "vue-winbox";

const options = {
  title: "Test",
};
</script>
```

The problem is that the controls (maximize, minimize, etc) cannot be clicked; the window can only be moved even if the mouse is over the controls on the top-right of the window. Should be something added in vite.config.js file ?

![2023-05-18_08h01_15](https://github.com/wobsoriano/vue-winbox/assets/68710312/45c7c232-03bd-4ed4-b163-58e6d2de6ef1)

**Comment by longhewang** [comment]
it works, see  https://playcode.io/1484702
