### ISSUE TITLE
Cannot read properties of null (reading 'classList')

### ISSUE THREAD

**Issue by ipacs13** [wobsoriano/vue-winbox#14]
Hi!

This component is so cool! However, I am having an issue currently on how to deal with this component in a modal.

1. I put `VueWinBox` in a modal component.
2. I close the modal
3. When I open the modal again, I see this issue
<img width="666" alt="image" src="https://github.com/wobsoriano/vue-winbox/assets/10388785/44aaccc2-37e5-4fe0-8173-98b86962edaf">

4. `VueWinBox` doesn't load anymore.

This is my code:

```
 <div
    @click.exact="close"
    class="modal fade slide-right"
    tabindex="-1"
    role="dialog"
    aria-hidden="true"
  >
    <ClientOnly>
      <VueWinBox
        v-if="editorOpen && viewportWidth >= 992"
        ref="winboxRef"
        :options="options"
        @close="close"
      >
        <!-- test only -->
        <iframe
          class="preview real"
          id="display-iframe"
          :src="previewUrl"
          frameborder="0"
          :key="previewUrl"
          @click.stop=""
        />
      </VueWinBox>
    </ClientOnly>
```

**Comment by wobsoriano** [comment]
Fixed in https://github.com/wobsoriano/vue-winbox/pull/12
