### ISSUE TITLE
open fail

### ISSUE THREAD

**Issue by PaiDaiXing** [wobsoriano/vue-winbox#17]
When I open the winbox on the page but do not close it, I switch the page. When I return to the page containing the winbox again, I find that it cannot be opened, and the error reported is TypeError: Cannot read properties of null (reading 'classList')
my code:

<script setup>
import { ref, onBeforeUnmount } from "vue";
import { VueWinBox, useWinBox } from "vue-winbox";

const options = {
  title: "demo",
  class: "modern",
  x: "center",
  y: "center",
  width: "60%",
  height: "75%",
};

const show = ref(false);
const winbox_ref = ref()
const handle_show = () => {
  show.value = true
}

const handle_close = () => {
  show.value = false
}

onBeforeUnmount(() => {
  show.value = false;
  winbox_ref.value.winbox.close();
})

</script>

**Comment by wobsoriano** [comment]
Please make a basic repro via https://stackblitz.com/
