### ISSUE TITLE
Nuxt Compatibility

### ISSUE THREAD

**Issue by g-tejas** [wobsoriano/vue-winbox#9]
I'm trying to get it to work with Nuxt-rc6 and vue3 but im running into "ReferenceError: document is not defined" errors. 

```vue
<template>
  <div>
      <VueWinBox></VueWinBox>
  </div>
</template>

<script setup>
import VueWinBox from 'vue-winbox';
const winboxRef = ref();

const options = {
  title: "Test",
  class: "Test2",
};
</script>
```

I'm guessing i need to import it as a plugin, but im not sure how to, would appreciate if someone could guide me, tysm in advance!

**Comment by wobsoriano** [comment]
You can create a winbox plugin in Nuxt and set it as client only.

Inside `plugins/winbox.client.ts`, you'll do:

```ts
import { VueWinBox } from 'vue-winbox'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('VueWinBox', VueWinBox)
})
```

Then use it anywhere in your app

```vue
<template>
  <div>
      <VueWinBox></VueWinBox>
  </div>
</template>

<script setup>
const winboxRef = ref();

const options = {
  title: "Test",
  class: "Test2",
};
</script>
```
